name: hg_app_2
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.0-nullsafety.2
  freezed_annotation: ^0.14.2
  cupertino_icons: ^1.0.2
  flash: ^2.0.0
  auto_route: ^2.2.0
  flutter_bloc: ^7.0.1
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  google_sign_in: ^5.0.4
  audioplayers: ^0.19.1
  hooks_riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/hooks_riverpod
  flutter_hooks: ^0.16.0
  flutter_launcher_icons: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  freezed: ^0.14.2
  auto_route_generator: ^2.1.0
  lint: ^1.5.3

dependency_overrides:
  flutter_riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/flutter_riverpod
  riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/riverpod

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/home.jpg'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/1.jpeg
    - assets/images/2.jpeg
    - assets/images/3.jpeg
    - assets/images/4.jpeg
    - assets/images/home.jpg
    - assets/images/grimm_brothers.jpeg
    - assets/images/karajan.png
    - assets/images/humperdinck.jpeg
    - assets/images/humperdincks.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
    - family: AmaticSC
      fonts:
        - asset: assets/fonts/AmaticSC-Regular.ttf
        - asset: assets/fonts/AmaticSC-Bold.ttf
          weight: 700
